// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePage = "page"

// Page mapped from table <page>
type Page struct {
	ID          int64      `gorm:"column:id;type:int(11);primaryKey" json:"id"`
	UID         int64      `gorm:"column:uid;type:bigint(20);not null" json:"uid"`
	Pid         string     `gorm:"column:pid;type:varchar(32);not null" json:"pid"`
	ReadonlyPid string     `gorm:"column:readonly_pid;type:varchar(32);not null" json:"readonly_pid"`
	EditPid     string     `gorm:"column:edit_pid;type:varchar(32);not null" json:"edit_pid"`
	AdminPid    string     `gorm:"column:admin_pid;type:varchar(32);not null" json:"admin_pid"`
	Title       string     `gorm:"column:title;type:varchar(128);not null" json:"title"`
	Content     string     `gorm:"column:content;type:mediumtext;not null" json:"content"`
	CreatedAt   *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Page's table name
func (*Page) TableName() string {
	return TableNamePage
}
