// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUniquePid = "unique_pid"

// UniquePid mapped from table <unique_pid>
type UniquePid struct {
	ID        int64      `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:auto increment ID" json:"id"`              // auto increment ID
	Pid       string     `gorm:"column:pid;type:varchar(16);not null;uniqueIndex:uk_pid,priority:1;comment:unique page id" json:"pid"`     // unique page id
	UID       int64      `gorm:"column:uid;type:bigint(20);not null;comment:user id" json:"uid"`                                           // user id
	CreatedAt *time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:create time" json:"created_at"` // create time
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:update time" json:"updated_at"` // update time
}

// TableName UniquePid's table name
func (*UniquePid) TableName() string {
	return TableNameUniquePid
}
