// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserPage = "user_page"

// UserPage mapped from table <user_page>
type UserPage struct {
	ID        int64          `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:auto increment ID" json:"id"`                           // auto increment ID
	UID       int64          `gorm:"column:uid;type:bigint(20);not null;uniqueIndex:uk_uid_pid,priority:1;comment:user id" json:"uid"`                      // user id
	Pid       string         `gorm:"column:pid;type:varchar(16);not null;uniqueIndex:uk_uid_pid,priority:2;comment:origin page id，start with O" json:"pid"` // origin page id，start with O
	Sort      int64          `gorm:"column:sort;type:int(11);not null;comment:sort order of page" json:"sort"`                                              // sort order of page
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:create time" json:"created_at"` // create time
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:update time" json:"updated_at"` // update time
}

// TableName UserPage's table name
func (*UserPage) TableName() string {
	return TableNameUserPage
}
