// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// versions:
// - protoc-gen-go-gin v1.0.3
// - protoc            v4.24.2
// source: api/proto/dumplinks.proto

package dumplinks

import (
	context "context"
	calloption "github.com/guoming0000/protoc-gen-go-gin/calloption"
	http_request "github.com/sunmi-OS/gocore/v2/utils/http-request"
)

// DumplinksServiceHTTPClient is the client API for DumplinksService service.
type DumplinksServiceHTTPClient interface {
	ImportBookmarks(context.Context, *ImportBookmarksReq, ...calloption.CallOption) (*TResponse[ImportBookmarksResp], error)
	ExportBookmarks(context.Context, *ExportBookmarksReq, ...calloption.CallOption) (*TResponse[ExportBookmarksResp], error)
}

type DumplinksServiceHTTPClientImpl struct {
	hh *http_request.HttpClient
}

func NewDumplinksServiceHTTPClient(hh *http_request.HttpClient) DumplinksServiceHTTPClient {
	return &DumplinksServiceHTTPClientImpl{hh: hh}
}
