// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/dumplinks.proto

package dumplinks

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
)

type ImportBookmarksReq struct {
	Folders []*Folder `json:"folders,omitempty"`
}

type Folder struct {
	Name     string   `json:"name,omitempty"`
	Bookmark []string `json:"bookmark,omitempty"`
}

type ImportBookmarksResp struct {
}

type ExportBookmarksReq struct {
}

type ExportBookmarksResp struct {
	Folders []*Folder `json:"folders,omitempty"`
}
