// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// versions:
// - protoc-gen-go-gin v1.0.3
// - protoc            v4.24.2
// source: api/proto/dumplinks.proto

package dumplinks

import (
	gin "github.com/gin-gonic/gin"
	api "github.com/sunmi-OS/gocore/v2/api"
)

// DumplinksServiceHTTPServer is the server API for DumplinksService service.
type DumplinksServiceHTTPServer interface {
	ImportBookmarks(*api.Context, *ImportBookmarksReq) (*ImportBookmarksResp, error)
	ExportBookmarks(*api.Context, *ExportBookmarksReq) (*ExportBookmarksResp, error)
}

func RegisterDumplinksServiceHTTPServer(s *gin.Engine, srv DumplinksServiceHTTPServer) {
	r := s.Group("/")
}
