// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// versions:
// - protoc-gen-go-gin v1.0.3
// - protoc            v4.24.2
// source: api/proto/dumplinks.proto

package dumplinks

import (
	sonic "github.com/bytedance/sonic"
)

func (m *Folder) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *Folder) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *Folder) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *Folder) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *ExportBookmarksReq) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *ExportBookmarksReq) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *ExportBookmarksReq) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *ExportBookmarksReq) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *ExportBookmarksResp) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *ExportBookmarksResp) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *ExportBookmarksResp) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *ExportBookmarksResp) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}
