// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/login.proto

package login

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
)

type LoginReq struct {
	// 用户名
	Username string `json:"username,omitempty"`
	// 前端加密后传给后端，不保存原文密码
	Password string `json:"password,omitempty"`
}

type LoginResp struct {
	// 成功则返回token，并且完成cookie的设置（记得要做cookie的弹窗功能）
	Token string `json:"token,omitempty"`
}

type RegisterReq struct {
	Username string `json:"username,omitempty"`
	Password string `json:"password,omitempty"`
	Email    string `json:"email,omitempty"`
}

type RegisterResp struct {
	Token string `json:"token,omitempty"`
}

type ConnectorReq struct {
	// 连接器名称：如weixin、google
	Name string `json:"name,omitempty"`
	// 连接器的入参
	Code string `json:"code,omitempty"`
}

type ConnectorResp struct {
}
