// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// versions:
// - protoc-gen-go-gin v1.0.3
// - protoc            v4.24.2
// source: api/proto/login.proto

package login

import (
	context "context"
	calloption "github.com/guoming0000/protoc-gen-go-gin/calloption"
	ecode "github.com/sunmi-OS/gocore/v2/api/ecode"
	http_request "github.com/sunmi-OS/gocore/v2/utils/http-request"
)

// LoginServiceHTTPClient is the client API for LoginService service.
type LoginServiceHTTPClient interface {
	Logout(context.Context, *LogoutReq, ...calloption.CallOption) (*TResponse[LogoutResp], error)
}

type LoginServiceHTTPClientImpl struct {
	hh *http_request.HttpClient
}

func NewLoginServiceHTTPClient(hh *http_request.HttpClient) LoginServiceHTTPClient {
	return &LoginServiceHTTPClientImpl{hh: hh}
}

func (c *LoginServiceHTTPClientImpl) Logout(ctx context.Context, req *LogoutReq, opts ...calloption.CallOption) (*TResponse[LogoutResp], error) {
	resp := &TResponse[LogoutResp]{}
	r := c.hh.Client.R().SetContext(ctx)
	for _, opt := range opts {
		opt(r)
	}
	_, err := r.SetBody(req).SetResult(resp).Post("/login/logout")
	if err != nil {
		return nil, err
	}
	if resp.Code != 1 {
		err = ecode.NewV2(int(resp.Code), resp.Msg)
	}
	return resp, err
}
