// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// versions:
// - protoc-gen-go-gin v1.0.3
// - protoc            v4.24.2
// source: api/proto/login.proto

package login

import (
	gin "github.com/gin-gonic/gin"
	api "github.com/sunmi-OS/gocore/v2/api"
)

// LoginServiceHTTPServer is the server API for LoginService service.
type LoginServiceHTTPServer interface {
	Logout(*api.Context, *LogoutReq) (*LogoutResp, error)
}

func RegisterLoginServiceHTTPServer(s *gin.Engine, srv LoginServiceHTTPServer) {
	r := s.Group("/")
	r.POST("/login/logout", _LoginService_Logout_HTTP_Handler(srv))
}

func _LoginService_Logout_HTTP_Handler(srv LoginServiceHTTPServer) func(g *gin.Context) {
	return func(g *gin.Context) {
		req := &LogoutReq{}
		ctx := api.NewContext(g)
		resp, err := srv.Logout(&ctx, req)
		setRetJSON(&ctx, resp, err)
	}
}
