// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// versions:
// - protoc-gen-go-gin v1.0.3
// - protoc            v4.24.2
// source: api/proto/login.proto

package login

import (
	sonic "github.com/bytedance/sonic"
)

func (m *LoginReq) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *LoginReq) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *LoginReq) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *LoginReq) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *LoginResp) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *LoginResp) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *LoginResp) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *LoginResp) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *RegisterReq) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *RegisterReq) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *RegisterReq) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *RegisterReq) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *RegisterResp) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *RegisterResp) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *RegisterResp) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *RegisterResp) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *ConnectorReq) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *ConnectorReq) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *ConnectorReq) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *ConnectorReq) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *ConnectorResp) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *ConnectorResp) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *ConnectorResp) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *ConnectorResp) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}
