// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q         = new(Query)
	Page      *page
	UniquePid *uniquePid
	User      *user
	UserPage  *userPage
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Page = &Q.Page
	UniquePid = &Q.UniquePid
	User = &Q.User
	UserPage = &Q.UserPage
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:        db,
		Page:      newPage(db, opts...),
		UniquePid: newUniquePid(db, opts...),
		User:      newUser(db, opts...),
		UserPage:  newUserPage(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Page      page
	UniquePid uniquePid
	User      user
	UserPage  userPage
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:        db,
		Page:      q.Page.clone(db),
		UniquePid: q.UniquePid.clone(db),
		User:      q.User.clone(db),
		UserPage:  q.UserPage.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:        db,
		Page:      q.Page.replaceDB(db),
		UniquePid: q.UniquePid.replaceDB(db),
		User:      q.User.replaceDB(db),
		UserPage:  q.UserPage.replaceDB(db),
	}
}

type queryCtx struct {
	Page      *pageDo
	UniquePid *uniquePidDo
	User      *userDo
	UserPage  *userPageDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Page:      q.Page.WithContext(ctx),
		UniquePid: q.UniquePid.WithContext(ctx),
		User:      q.User.WithContext(ctx),
		UserPage:  q.UserPage.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
