// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"forgeturl-server/dal/model"
)

func newUniquePid(db *gorm.DB, opts ...gen.DOOption) uniquePid {
	_uniquePid := uniquePid{}

	_uniquePid.uniquePidDo.UseDB(db, opts...)
	_uniquePid.uniquePidDo.UseModel(&model.UniquePid{})

	tableName := _uniquePid.uniquePidDo.TableName()
	_uniquePid.ALL = field.NewAsterisk(tableName)
	_uniquePid.ID = field.NewInt64(tableName, "id")
	_uniquePid.Pid = field.NewString(tableName, "pid")
	_uniquePid.UID = field.NewInt64(tableName, "uid")
	_uniquePid.CreatedAt = field.NewTime(tableName, "created_at")
	_uniquePid.UpdatedAt = field.NewTime(tableName, "updated_at")

	_uniquePid.fillFieldMap()

	return _uniquePid
}

type uniquePid struct {
	uniquePidDo uniquePidDo

	ALL       field.Asterisk
	ID        field.Int64  // auto increment ID
	Pid       field.String // unique page id
	UID       field.Int64  // user id
	CreatedAt field.Time   // create time
	UpdatedAt field.Time   // update time

	fieldMap map[string]field.Expr
}

func (u uniquePid) Table(newTableName string) *uniquePid {
	u.uniquePidDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u uniquePid) As(alias string) *uniquePid {
	u.uniquePidDo.DO = *(u.uniquePidDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *uniquePid) updateTableName(table string) *uniquePid {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt64(table, "id")
	u.Pid = field.NewString(table, "pid")
	u.UID = field.NewInt64(table, "uid")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")

	u.fillFieldMap()

	return u
}

func (u *uniquePid) WithContext(ctx context.Context) *uniquePidDo {
	return u.uniquePidDo.WithContext(ctx)
}

func (u uniquePid) TableName() string { return u.uniquePidDo.TableName() }

func (u uniquePid) Alias() string { return u.uniquePidDo.Alias() }

func (u uniquePid) Columns(cols ...field.Expr) gen.Columns { return u.uniquePidDo.Columns(cols...) }

func (u *uniquePid) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *uniquePid) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 5)
	u.fieldMap["id"] = u.ID
	u.fieldMap["pid"] = u.Pid
	u.fieldMap["uid"] = u.UID
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
}

func (u uniquePid) clone(db *gorm.DB) uniquePid {
	u.uniquePidDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u uniquePid) replaceDB(db *gorm.DB) uniquePid {
	u.uniquePidDo.ReplaceDB(db)
	return u
}

type uniquePidDo struct{ gen.DO }

func (u uniquePidDo) Debug() *uniquePidDo {
	return u.withDO(u.DO.Debug())
}

func (u uniquePidDo) WithContext(ctx context.Context) *uniquePidDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u uniquePidDo) ReadDB() *uniquePidDo {
	return u.Clauses(dbresolver.Read)
}

func (u uniquePidDo) WriteDB() *uniquePidDo {
	return u.Clauses(dbresolver.Write)
}

func (u uniquePidDo) Session(config *gorm.Session) *uniquePidDo {
	return u.withDO(u.DO.Session(config))
}

func (u uniquePidDo) Clauses(conds ...clause.Expression) *uniquePidDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u uniquePidDo) Returning(value interface{}, columns ...string) *uniquePidDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u uniquePidDo) Not(conds ...gen.Condition) *uniquePidDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u uniquePidDo) Or(conds ...gen.Condition) *uniquePidDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u uniquePidDo) Select(conds ...field.Expr) *uniquePidDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u uniquePidDo) Where(conds ...gen.Condition) *uniquePidDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u uniquePidDo) Order(conds ...field.Expr) *uniquePidDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u uniquePidDo) Distinct(cols ...field.Expr) *uniquePidDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u uniquePidDo) Omit(cols ...field.Expr) *uniquePidDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u uniquePidDo) Join(table schema.Tabler, on ...field.Expr) *uniquePidDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u uniquePidDo) LeftJoin(table schema.Tabler, on ...field.Expr) *uniquePidDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u uniquePidDo) RightJoin(table schema.Tabler, on ...field.Expr) *uniquePidDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u uniquePidDo) Group(cols ...field.Expr) *uniquePidDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u uniquePidDo) Having(conds ...gen.Condition) *uniquePidDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u uniquePidDo) Limit(limit int) *uniquePidDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u uniquePidDo) Offset(offset int) *uniquePidDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u uniquePidDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *uniquePidDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u uniquePidDo) Unscoped() *uniquePidDo {
	return u.withDO(u.DO.Unscoped())
}

func (u uniquePidDo) Create(values ...*model.UniquePid) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u uniquePidDo) CreateInBatches(values []*model.UniquePid, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u uniquePidDo) Save(values ...*model.UniquePid) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u uniquePidDo) First() (*model.UniquePid, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UniquePid), nil
	}
}

func (u uniquePidDo) Take() (*model.UniquePid, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UniquePid), nil
	}
}

func (u uniquePidDo) Last() (*model.UniquePid, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UniquePid), nil
	}
}

func (u uniquePidDo) Find() ([]*model.UniquePid, error) {
	result, err := u.DO.Find()
	return result.([]*model.UniquePid), err
}

func (u uniquePidDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UniquePid, err error) {
	buf := make([]*model.UniquePid, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u uniquePidDo) FindInBatches(result *[]*model.UniquePid, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u uniquePidDo) Attrs(attrs ...field.AssignExpr) *uniquePidDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u uniquePidDo) Assign(attrs ...field.AssignExpr) *uniquePidDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u uniquePidDo) Joins(fields ...field.RelationField) *uniquePidDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u uniquePidDo) Preload(fields ...field.RelationField) *uniquePidDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u uniquePidDo) FirstOrInit() (*model.UniquePid, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UniquePid), nil
	}
}

func (u uniquePidDo) FirstOrCreate() (*model.UniquePid, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UniquePid), nil
	}
}

func (u uniquePidDo) FindByPage(offset int, limit int) (result []*model.UniquePid, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u uniquePidDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u uniquePidDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u uniquePidDo) Delete(models ...*model.UniquePid) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *uniquePidDo) withDO(do gen.Dao) *uniquePidDo {
	u.DO = *do.(*gen.DO)
	return u
}
