// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// versions:
// - protoc-gen-go-gin v1.0.3
// - protoc            v4.24.2
// source: api/proto/openclaw.proto

package openclaw

import (
	context "context"
	calloption "github.com/guoming0000/protoc-gen-go-gin/calloption"
	ecode "github.com/sunmi-OS/gocore/v2/api/ecode"
	http_request "github.com/sunmi-OS/gocore/v2/utils/http-request"
)

// OpenClawServiceHTTPClient is the client API for OpenClawService service.
type OpenClawServiceHTTPClient interface {
	GetApiKey(context.Context, *GetApiKeyReq, ...calloption.CallOption) (*TResponse[GetApiKeyResp], error)
	RegenerateApiKey(context.Context, *RegenerateApiKeyReq, ...calloption.CallOption) (*TResponse[RegenerateApiKeyResp], error)
	AddTmpBookmark(context.Context, *AddTmpBookmarkReq, ...calloption.CallOption) (*TResponse[AddTmpBookmarkResp], error)
	ListTmpBookmarks(context.Context, *ListTmpBookmarksReq, ...calloption.CallOption) (*TResponse[ListTmpBookmarksResp], error)
	ExistsTmpBookmark(context.Context, *ExistsTmpBookmarkReq, ...calloption.CallOption) (*TResponse[ExistsTmpBookmarkResp], error)
	MoveTmpBookmarkToPage(context.Context, *MoveTmpBookmarkToPageReq, ...calloption.CallOption) (*TResponse[EmptyResp], error)
	MovePageBookmarkToTmp(context.Context, *MovePageBookmarkToTmpReq, ...calloption.CallOption) (*TResponse[EmptyResp], error)
}

type OpenClawServiceHTTPClientImpl struct {
	hh *http_request.HttpClient
}

func NewOpenClawServiceHTTPClient(hh *http_request.HttpClient) OpenClawServiceHTTPClient {
	return &OpenClawServiceHTTPClientImpl{hh: hh}
}

func (c *OpenClawServiceHTTPClientImpl) GetApiKey(ctx context.Context, req *GetApiKeyReq, opts ...calloption.CallOption) (*TResponse[GetApiKeyResp], error) {
	resp := &TResponse[GetApiKeyResp]{}
	r := c.hh.Client.R().SetContext(ctx)
	for _, opt := range opts {
		opt(r)
	}
	_, err := r.SetBody(req).SetResult(resp).Post("/openclaw/getApiKey")
	if err != nil {
		return nil, err
	}
	if resp.Code != 1 {
		err = ecode.NewV2(int(resp.Code), resp.Msg)
	}
	return resp, err
}

func (c *OpenClawServiceHTTPClientImpl) RegenerateApiKey(ctx context.Context, req *RegenerateApiKeyReq, opts ...calloption.CallOption) (*TResponse[RegenerateApiKeyResp], error) {
	resp := &TResponse[RegenerateApiKeyResp]{}
	r := c.hh.Client.R().SetContext(ctx)
	for _, opt := range opts {
		opt(r)
	}
	_, err := r.SetBody(req).SetResult(resp).Post("/openclaw/regenerateApiKey")
	if err != nil {
		return nil, err
	}
	if resp.Code != 1 {
		err = ecode.NewV2(int(resp.Code), resp.Msg)
	}
	return resp, err
}

func (c *OpenClawServiceHTTPClientImpl) AddTmpBookmark(ctx context.Context, req *AddTmpBookmarkReq, opts ...calloption.CallOption) (*TResponse[AddTmpBookmarkResp], error) {
	resp := &TResponse[AddTmpBookmarkResp]{}
	r := c.hh.Client.R().SetContext(ctx)
	for _, opt := range opts {
		opt(r)
	}
	_, err := r.SetBody(req).SetResult(resp).Post("/openclaw/tmpBookmark/add")
	if err != nil {
		return nil, err
	}
	if resp.Code != 1 {
		err = ecode.NewV2(int(resp.Code), resp.Msg)
	}
	return resp, err
}

func (c *OpenClawServiceHTTPClientImpl) ListTmpBookmarks(ctx context.Context, req *ListTmpBookmarksReq, opts ...calloption.CallOption) (*TResponse[ListTmpBookmarksResp], error) {
	resp := &TResponse[ListTmpBookmarksResp]{}
	r := c.hh.Client.R().SetContext(ctx)
	for _, opt := range opts {
		opt(r)
	}
	_, err := r.SetBody(req).SetResult(resp).Post("/openclaw/tmpBookmark/list")
	if err != nil {
		return nil, err
	}
	if resp.Code != 1 {
		err = ecode.NewV2(int(resp.Code), resp.Msg)
	}
	return resp, err
}

func (c *OpenClawServiceHTTPClientImpl) ExistsTmpBookmark(ctx context.Context, req *ExistsTmpBookmarkReq, opts ...calloption.CallOption) (*TResponse[ExistsTmpBookmarkResp], error) {
	resp := &TResponse[ExistsTmpBookmarkResp]{}
	r := c.hh.Client.R().SetContext(ctx)
	for _, opt := range opts {
		opt(r)
	}
	_, err := r.SetBody(req).SetResult(resp).Post("/openclaw/tmpBookmark/exists")
	if err != nil {
		return nil, err
	}
	if resp.Code != 1 {
		err = ecode.NewV2(int(resp.Code), resp.Msg)
	}
	return resp, err
}

func (c *OpenClawServiceHTTPClientImpl) MoveTmpBookmarkToPage(ctx context.Context, req *MoveTmpBookmarkToPageReq, opts ...calloption.CallOption) (*TResponse[EmptyResp], error) {
	resp := &TResponse[EmptyResp]{}
	r := c.hh.Client.R().SetContext(ctx)
	for _, opt := range opts {
		opt(r)
	}
	_, err := r.SetBody(req).SetResult(resp).Post("/openclaw/tmpBookmark/moveToPage")
	if err != nil {
		return nil, err
	}
	if resp.Code != 1 {
		err = ecode.NewV2(int(resp.Code), resp.Msg)
	}
	return resp, err
}

func (c *OpenClawServiceHTTPClientImpl) MovePageBookmarkToTmp(ctx context.Context, req *MovePageBookmarkToTmpReq, opts ...calloption.CallOption) (*TResponse[EmptyResp], error) {
	resp := &TResponse[EmptyResp]{}
	r := c.hh.Client.R().SetContext(ctx)
	for _, opt := range opts {
		opt(r)
	}
	_, err := r.SetBody(req).SetResult(resp).Post("/openclaw/tmpBookmark/moveFromPage")
	if err != nil {
		return nil, err
	}
	if resp.Code != 1 {
		err = ecode.NewV2(int(resp.Code), resp.Msg)
	}
	return resp, err
}
