// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// versions:
// - protoc-gen-go-gin v1.0.3
// - protoc            v4.24.2
// source: api/proto/openclaw.proto

package openclaw

import (
	sonic "github.com/bytedance/sonic"
)

func (m *GetApiKeyReq) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *GetApiKeyReq) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *GetApiKeyReq) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *GetApiKeyReq) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *GetApiKeyResp) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *GetApiKeyResp) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *GetApiKeyResp) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *GetApiKeyResp) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *RegenerateApiKeyReq) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *RegenerateApiKeyReq) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *RegenerateApiKeyReq) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *RegenerateApiKeyReq) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *RegenerateApiKeyResp) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *RegenerateApiKeyResp) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *RegenerateApiKeyResp) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *RegenerateApiKeyResp) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *TmpBookmark) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *TmpBookmark) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *TmpBookmark) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *TmpBookmark) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *AddTmpBookmarkReq) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *AddTmpBookmarkReq) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *AddTmpBookmarkReq) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *AddTmpBookmarkReq) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *AddTmpBookmarkResp) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *AddTmpBookmarkResp) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *AddTmpBookmarkResp) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *AddTmpBookmarkResp) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *ListTmpBookmarksReq) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *ListTmpBookmarksReq) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *ListTmpBookmarksReq) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *ListTmpBookmarksReq) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *ListTmpBookmarksResp) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *ListTmpBookmarksResp) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *ListTmpBookmarksResp) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *ListTmpBookmarksResp) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *ExistsTmpBookmarkReq) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *ExistsTmpBookmarkReq) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *ExistsTmpBookmarkReq) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *ExistsTmpBookmarkReq) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *ExistsTmpBookmarkResp) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *ExistsTmpBookmarkResp) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *ExistsTmpBookmarkResp) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *ExistsTmpBookmarkResp) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *MoveTmpBookmarkToPageReq) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *MoveTmpBookmarkToPageReq) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *MoveTmpBookmarkToPageReq) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *MoveTmpBookmarkToPageReq) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *MovePageBookmarkToTmpReq) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *MovePageBookmarkToTmpReq) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *MovePageBookmarkToTmpReq) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *MovePageBookmarkToTmpReq) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *EmptyResp) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *EmptyResp) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *EmptyResp) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *EmptyResp) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}
