// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/openclaw.proto

package openclaw

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
)

type GetApiKeyReq struct {
}

type GetApiKeyResp struct {
	HasKey bool   `json:"has_key"`
	ApiKey string `json:"api_key"`
}

type RegenerateApiKeyReq struct {
}

type RegenerateApiKeyResp struct {
	ApiKey string `json:"api_key"`
}

type TmpBookmark struct {
	Id       int64  `json:"id"`
	Title    string `json:"title"`
	Url      string `json:"url"`
	CreateAt int64  `json:"create_at"`
	UpdateAt int64  `json:"update_at"`
}

type AddTmpBookmarkReq struct {
	Title string `json:"title" binding:"required,min=1,max=256"`
	Url   string `json:"url" binding:"required,min=1,max=2048"`
}

type AddTmpBookmarkResp struct {
	Bookmark *TmpBookmark `json:"bookmark"`
}

type ListTmpBookmarksReq struct {
	Limit int32 `json:"limit,omitempty" binding:"min=0,max=500"`
}

type ListTmpBookmarksResp struct {
	Bookmarks []*TmpBookmark `json:"bookmarks"`
}

type ExistsTmpBookmarkReq struct {
	Title string `json:"title" binding:"required,min=1,max=256"`
	Url   string `json:"url" binding:"required,min=1,max=2048"`
}

type ExistsTmpBookmarkResp struct {
	Exists   bool         `json:"exists"`
	Bookmark *TmpBookmark `json:"bookmark"`
}

type MoveTmpBookmarkToPageReq struct {
	BookmarkId      int64  `json:"bookmark_id" binding:"required,min=1"`
	PageId          string `json:"page_id" binding:"required,min=1,max=64"`
	CollectionTitle string `json:"collection_title,omitempty" binding:"max=256"`
}

type MovePageBookmarkToTmpReq struct {
	PageId          string `json:"page_id" binding:"required,min=1,max=64"`
	CollectionTitle string `json:"collection_title,omitempty" binding:"max=256"`
	Title           string `json:"title" binding:"required,min=1,max=256"`
	Url             string `json:"url" binding:"required,min=1,max=2048"`
}

type EmptyResp struct {
}
