// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// versions:
// - protoc-gen-go-gin v1.0.3
// - protoc            v4.24.2
// source: api/proto/openclaw.proto

package openclaw

import (
	gin "github.com/gin-gonic/gin"
	api "github.com/sunmi-OS/gocore/v2/api"
)

// OpenClawServiceHTTPServer is the server API for OpenClawService service.
type OpenClawServiceHTTPServer interface {
	GetApiKey(*api.Context, *GetApiKeyReq) (*GetApiKeyResp, error)
	RegenerateApiKey(*api.Context, *RegenerateApiKeyReq) (*RegenerateApiKeyResp, error)
	AddTmpBookmark(*api.Context, *AddTmpBookmarkReq) (*AddTmpBookmarkResp, error)
	ListTmpBookmarks(*api.Context, *ListTmpBookmarksReq) (*ListTmpBookmarksResp, error)
	ExistsTmpBookmark(*api.Context, *ExistsTmpBookmarkReq) (*ExistsTmpBookmarkResp, error)
	MoveTmpBookmarkToPage(*api.Context, *MoveTmpBookmarkToPageReq) (*EmptyResp, error)
	MovePageBookmarkToTmp(*api.Context, *MovePageBookmarkToTmpReq) (*EmptyResp, error)
}

func RegisterOpenClawServiceHTTPServer(s *gin.Engine, srv OpenClawServiceHTTPServer) {
	r := s.Group("/")
	r.POST("/openclaw/getApiKey", _OpenClawService_GetApiKey_HTTP_Handler(srv))
	r.POST("/openclaw/regenerateApiKey", _OpenClawService_RegenerateApiKey_HTTP_Handler(srv))
	r.POST("/openclaw/tmpBookmark/add", _OpenClawService_AddTmpBookmark_HTTP_Handler(srv))
	r.POST("/openclaw/tmpBookmark/list", _OpenClawService_ListTmpBookmarks_HTTP_Handler(srv))
	r.POST("/openclaw/tmpBookmark/exists", _OpenClawService_ExistsTmpBookmark_HTTP_Handler(srv))
	r.POST("/openclaw/tmpBookmark/moveToPage", _OpenClawService_MoveTmpBookmarkToPage_HTTP_Handler(srv))
	r.POST("/openclaw/tmpBookmark/moveFromPage", _OpenClawService_MovePageBookmarkToTmp_HTTP_Handler(srv))
}

func _OpenClawService_GetApiKey_HTTP_Handler(srv OpenClawServiceHTTPServer) func(g *gin.Context) {
	return func(g *gin.Context) {
		req := &GetApiKeyReq{}
		ctx := api.NewContext(g)
		resp, err := srv.GetApiKey(&ctx, req)
		setRetJSON(&ctx, resp, err)
	}
}

func _OpenClawService_RegenerateApiKey_HTTP_Handler(srv OpenClawServiceHTTPServer) func(g *gin.Context) {
	return func(g *gin.Context) {
		req := &RegenerateApiKeyReq{}
		ctx := api.NewContext(g)
		resp, err := srv.RegenerateApiKey(&ctx, req)
		setRetJSON(&ctx, resp, err)
	}
}

func _OpenClawService_AddTmpBookmark_HTTP_Handler(srv OpenClawServiceHTTPServer) func(g *gin.Context) {
	return func(g *gin.Context) {
		req := &AddTmpBookmarkReq{}
		var err error
		ctx := api.NewContext(g)
		err = parseReq(&ctx, req)
		err = checkValidate(err)
		if err != nil {
			setRetJSON(&ctx, nil, err)
			return
		}
		resp, err := srv.AddTmpBookmark(&ctx, req)
		setRetJSON(&ctx, resp, err)
	}
}

func _OpenClawService_ListTmpBookmarks_HTTP_Handler(srv OpenClawServiceHTTPServer) func(g *gin.Context) {
	return func(g *gin.Context) {
		req := &ListTmpBookmarksReq{}
		var err error
		ctx := api.NewContext(g)
		err = parseReq(&ctx, req)
		err = checkValidate(err)
		if err != nil {
			setRetJSON(&ctx, nil, err)
			return
		}
		resp, err := srv.ListTmpBookmarks(&ctx, req)
		setRetJSON(&ctx, resp, err)
	}
}

func _OpenClawService_ExistsTmpBookmark_HTTP_Handler(srv OpenClawServiceHTTPServer) func(g *gin.Context) {
	return func(g *gin.Context) {
		req := &ExistsTmpBookmarkReq{}
		var err error
		ctx := api.NewContext(g)
		err = parseReq(&ctx, req)
		err = checkValidate(err)
		if err != nil {
			setRetJSON(&ctx, nil, err)
			return
		}
		resp, err := srv.ExistsTmpBookmark(&ctx, req)
		setRetJSON(&ctx, resp, err)
	}
}

func _OpenClawService_MoveTmpBookmarkToPage_HTTP_Handler(srv OpenClawServiceHTTPServer) func(g *gin.Context) {
	return func(g *gin.Context) {
		req := &MoveTmpBookmarkToPageReq{}
		var err error
		ctx := api.NewContext(g)
		err = parseReq(&ctx, req)
		err = checkValidate(err)
		if err != nil {
			setRetJSON(&ctx, nil, err)
			return
		}
		resp, err := srv.MoveTmpBookmarkToPage(&ctx, req)
		setRetJSON(&ctx, resp, err)
	}
}

func _OpenClawService_MovePageBookmarkToTmp_HTTP_Handler(srv OpenClawServiceHTTPServer) func(g *gin.Context) {
	return func(g *gin.Context) {
		req := &MovePageBookmarkToTmpReq{}
		var err error
		ctx := api.NewContext(g)
		err = parseReq(&ctx, req)
		err = checkValidate(err)
		if err != nil {
			setRetJSON(&ctx, nil, err)
			return
		}
		resp, err := srv.MovePageBookmarkToTmp(&ctx, req)
		setRetJSON(&ctx, resp, err)
	}
}
