// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// versions:
// - protoc-gen-go-gin v1.0.3
// - protoc            v4.24.2
// source: api/proto/space.proto

package space

import (
	sonic "github.com/bytedance/sonic"
)

func (m *CreateTmpPageReq) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *CreateTmpPageReq) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *CreateTmpPageReq) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *CreateTmpPageReq) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *CreateTmpPageResp) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *CreateTmpPageResp) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *CreateTmpPageResp) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *CreateTmpPageResp) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *Page) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *Page) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *Page) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *Page) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *PageBrief) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *PageBrief) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *PageBrief) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *PageBrief) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *Collections) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *Collections) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *Collections) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *Collections) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *SubLink) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *SubLink) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *SubLink) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *SubLink) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *Link) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *Link) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *Link) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *Link) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *PageConf) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *PageConf) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *PageConf) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *PageConf) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *GetPageReq) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *GetPageReq) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *GetPageReq) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *GetPageReq) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *GetPageResp) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *GetPageResp) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *GetPageResp) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *GetPageResp) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *GetMySpaceReq) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *GetMySpaceReq) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *GetMySpaceReq) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *GetMySpaceReq) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *GetMySpaceResp) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *GetMySpaceResp) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *GetMySpaceResp) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *GetMySpaceResp) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *SavePageIdsReq) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *SavePageIdsReq) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *SavePageIdsReq) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *SavePageIdsReq) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *SavePageIdsResp) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *SavePageIdsResp) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *SavePageIdsResp) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *SavePageIdsResp) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *UpdatePageReq) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *UpdatePageReq) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *UpdatePageReq) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *UpdatePageReq) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *UpdatePageResp) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *UpdatePageResp) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *UpdatePageResp) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *UpdatePageResp) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *DeletePageReq) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *DeletePageReq) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *DeletePageReq) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *DeletePageReq) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *DeletePageResp) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *DeletePageResp) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *DeletePageResp) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *DeletePageResp) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *RemovePageLinkReq) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *RemovePageLinkReq) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *RemovePageLinkReq) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *RemovePageLinkReq) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *RemovePageLinkResp) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *RemovePageLinkResp) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *RemovePageLinkResp) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *RemovePageLinkResp) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *CreatePageLinkReq) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *CreatePageLinkReq) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *CreatePageLinkReq) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *CreatePageLinkReq) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}

func (m *CreatePageLinkResp) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *CreatePageLinkResp) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *CreatePageLinkResp) Unmarshal(buf []byte) error {
	return sonic.Unmarshal(buf, m)
}

func (m *CreatePageLinkResp) UnmarshalString(str string) error {
	return sonic.UnmarshalString(str, m)
}
