// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// versions:
// - protoc-gen-go-gin v1.0.3
// - protoc            v4.24.2
// source: api/proto/space.proto

package space

import (
	context "context"
	calloption "github.com/guoming0000/protoc-gen-go-gin/calloption"
	ecode "github.com/sunmi-OS/gocore/v2/api/ecode"
	http_request "github.com/sunmi-OS/gocore/v2/utils/http-request"
)

// SpaceServiceHTTPClient is the client API for SpaceService service.
type SpaceServiceHTTPClient interface {
	// 拉取我的空间 || 空间
	// 登录状态才能拉到自己的空间
	// 部分页面如果消失或者没权限了，需要自动移除
	GetMySpace(context.Context, *GetMySpaceReq, ...calloption.CallOption) (*TResponse[GetMySpaceResp], error)
	// 调整我的空间下面的页面顺序 || 空间
	ChangeSpacePageSequence(context.Context, *ChangeSpacePageSequenceReq, ...calloption.CallOption) (*TResponse[ChangeSpacePageSequenceResp], error)
	// 创建临时页面 || 页面
	// 非登录状态可以创建临时页面，默认一个浏览器只能创建一个自己的临时页面
	// 创建完成后得到一个随机页面id(比如 240626-abcd)，不使用lo等字符串，只使用其他字母
	// 生成算法：当前时间转换的4个字母(时分秒)
	CreateTmpPage(context.Context, *CreateTmpPageReq, ...calloption.CallOption) (*TResponse[CreateTmpPageResp], error)
	// 拉取某个页面数据 || 页面
	// 拉取某个页面
	// 临时页面，可以读到
	GetPages(context.Context, *GetPagesReq, ...calloption.CallOption) (*TResponse[GetPagesResp], error)
	// 拉取某个页面数据 || 页面
	GetPage(context.Context, *GetPageReq, ...calloption.CallOption) (*TResponse[GetPageResp], error)
	// 更新页面 || 页面
	UpdatePage(context.Context, *UpdatePageReq, ...calloption.CallOption) (*TResponse[UpdatePageResp], error)
	// 把整个页面删除 || 页面
	// 自己的默认页面只能清空，无法删除
	DeletePage(context.Context, *DeletePageReq, ...calloption.CallOption) (*TResponse[DeletePageResp], error)
	// 去除页面连接 || 页面
	// 把页面的只读链接删除
	RemovePageLink(context.Context, *RemovePageLinkReq, ...calloption.CallOption) (*TResponse[RemovePageLinkResp], error)
	// 生成新页面链接 || 页面
	CreateNewPageLink(context.Context, *CreateNewPageLinkReq, ...calloption.CallOption) (*TResponse[CreateNewPageLinkResp], error)
}

type SpaceServiceHTTPClientImpl struct {
	hh *http_request.HttpClient
}

func NewSpaceServiceHTTPClient(hh *http_request.HttpClient) SpaceServiceHTTPClient {
	return &SpaceServiceHTTPClientImpl{hh: hh}
}

func (c *SpaceServiceHTTPClientImpl) GetMySpace(ctx context.Context, req *GetMySpaceReq, opts ...calloption.CallOption) (*TResponse[GetMySpaceResp], error) {
	resp := &TResponse[GetMySpaceResp]{}
	r := c.hh.Client.R().SetContext(ctx)
	for _, opt := range opts {
		opt(r)
	}
	_, err := r.SetBody(req).SetResult(resp).Post("/page/getMySpace")
	if err != nil {
		return nil, err
	}
	if resp.Code != 1 {
		err = ecode.NewV2(int(resp.Code), resp.Msg)
	}
	return resp, err
}

func (c *SpaceServiceHTTPClientImpl) ChangeSpacePageSequence(ctx context.Context, req *ChangeSpacePageSequenceReq, opts ...calloption.CallOption) (*TResponse[ChangeSpacePageSequenceResp], error) {
	resp := &TResponse[ChangeSpacePageSequenceResp]{}
	r := c.hh.Client.R().SetContext(ctx)
	for _, opt := range opts {
		opt(r)
	}
	_, err := r.SetBody(req).SetResult(resp).Post("/page/changeSpacePageSequence")
	if err != nil {
		return nil, err
	}
	if resp.Code != 1 {
		err = ecode.NewV2(int(resp.Code), resp.Msg)
	}
	return resp, err
}

func (c *SpaceServiceHTTPClientImpl) CreateTmpPage(ctx context.Context, req *CreateTmpPageReq, opts ...calloption.CallOption) (*TResponse[CreateTmpPageResp], error) {
	resp := &TResponse[CreateTmpPageResp]{}
	r := c.hh.Client.R().SetContext(ctx)
	for _, opt := range opts {
		opt(r)
	}
	_, err := r.SetBody(req).SetResult(resp).Post("/page/createTmpPage")
	if err != nil {
		return nil, err
	}
	if resp.Code != 1 {
		err = ecode.NewV2(int(resp.Code), resp.Msg)
	}
	return resp, err
}

func (c *SpaceServiceHTTPClientImpl) GetPages(ctx context.Context, req *GetPagesReq, opts ...calloption.CallOption) (*TResponse[GetPagesResp], error) {
	resp := &TResponse[GetPagesResp]{}
	r := c.hh.Client.R().SetContext(ctx)
	for _, opt := range opts {
		opt(r)
	}
	_, err := r.SetBody(req).SetResult(resp).Post("/page/getPages")
	if err != nil {
		return nil, err
	}
	if resp.Code != 1 {
		err = ecode.NewV2(int(resp.Code), resp.Msg)
	}
	return resp, err
}

func (c *SpaceServiceHTTPClientImpl) GetPage(ctx context.Context, req *GetPageReq, opts ...calloption.CallOption) (*TResponse[GetPageResp], error) {
	resp := &TResponse[GetPageResp]{}
	r := c.hh.Client.R().SetContext(ctx)
	for _, opt := range opts {
		opt(r)
	}
	_, err := r.SetBody(req).SetResult(resp).Post("/page/getPage")
	if err != nil {
		return nil, err
	}
	if resp.Code != 1 {
		err = ecode.NewV2(int(resp.Code), resp.Msg)
	}
	return resp, err
}

func (c *SpaceServiceHTTPClientImpl) UpdatePage(ctx context.Context, req *UpdatePageReq, opts ...calloption.CallOption) (*TResponse[UpdatePageResp], error) {
	resp := &TResponse[UpdatePageResp]{}
	r := c.hh.Client.R().SetContext(ctx)
	for _, opt := range opts {
		opt(r)
	}
	_, err := r.SetBody(req).SetResult(resp).Post("/page/updatePage")
	if err != nil {
		return nil, err
	}
	if resp.Code != 1 {
		err = ecode.NewV2(int(resp.Code), resp.Msg)
	}
	return resp, err
}

func (c *SpaceServiceHTTPClientImpl) DeletePage(ctx context.Context, req *DeletePageReq, opts ...calloption.CallOption) (*TResponse[DeletePageResp], error) {
	resp := &TResponse[DeletePageResp]{}
	r := c.hh.Client.R().SetContext(ctx)
	for _, opt := range opts {
		opt(r)
	}
	_, err := r.SetBody(req).SetResult(resp).Post("/page/deletePage")
	if err != nil {
		return nil, err
	}
	if resp.Code != 1 {
		err = ecode.NewV2(int(resp.Code), resp.Msg)
	}
	return resp, err
}

func (c *SpaceServiceHTTPClientImpl) RemovePageLink(ctx context.Context, req *RemovePageLinkReq, opts ...calloption.CallOption) (*TResponse[RemovePageLinkResp], error) {
	resp := &TResponse[RemovePageLinkResp]{}
	r := c.hh.Client.R().SetContext(ctx)
	for _, opt := range opts {
		opt(r)
	}
	_, err := r.SetBody(req).SetResult(resp).Post("/page/removePageLink")
	if err != nil {
		return nil, err
	}
	if resp.Code != 1 {
		err = ecode.NewV2(int(resp.Code), resp.Msg)
	}
	return resp, err
}

func (c *SpaceServiceHTTPClientImpl) CreateNewPageLink(ctx context.Context, req *CreateNewPageLinkReq, opts ...calloption.CallOption) (*TResponse[CreateNewPageLinkResp], error) {
	resp := &TResponse[CreateNewPageLinkResp]{}
	r := c.hh.Client.R().SetContext(ctx)
	for _, opt := range opts {
		opt(r)
	}
	_, err := r.SetBody(req).SetResult(resp).Post("/page/createNewPageLink")
	if err != nil {
		return nil, err
	}
	if resp.Code != 1 {
		err = ecode.NewV2(int(resp.Code), resp.Msg)
	}
	return resp, err
}
